/* 
 * Language file for SWAC internationalization
 */
let core_en = {
    waitingbackend: "The app is starting. Please be patient.",
    sourceerror: 'One datasource is not available. Will try it again soon.',
    loaderror: 'Application could not be loaded. Click ok to try again.',
    loadingdata: "Loading data",
    loadingtemplate: "Loading view",
    showWhenNoData: "With this option set to true the component will be shown even if there is no data.",
    model_nodata: 'No data available',
    model_savesuccsess: 'Data saved succsessfully',
    model_saveerror: 'Sorry, data could not be saved',
    remote_backenderror: "Sorry, an error occured",
    save: 'Save',
    saveall: 'Save all',
    savetofileerr: 'Could not save changes to datasets that where loaded from a static file.',
    delete: 'Delete',
    moreerrors: "There occured %number% more errors.",
    sortChildsSorting: 'Sorting data for %requestor_id%',
    savesuccsess: 'Data saved succsessfully',
    saveerror: 'Error while saveing',
    updatesuccsess: 'Update succsessfull',
    updateerror: 'Error while updateing',
    deletesuccsess: 'Dataset was deleted',
    deleteerror: 'Error while deleting',
    appOffline: 'You are working offline. Connect to a network to continue.',
    appOfflineProgressive: 'You are working offline. Data will be synchronised as you reconnect.',
    appUnreachable: 'The network app is currently not available. Please try later.',
    appUnreachableProgressive: 'The network app is currently not available. Data will be synchronised as youre reconnected.',
    loadFailLogin: 'You have to be logged in, to see something here.',
    loadFailRight: 'You have not the right to access this content.',
    loadFailErr: 'An error occured while loading data from %source%.',
    day_0: 'Sun',
    day_1: 'Mon',
    day_2: 'Tue',
    day_3: 'Wed',
    day_4: 'Thur',
    day_5: 'Fri',
    day_6: 'Sat',
    view_adddata: 'Add data',
    contenttype_unsupported: 'Sorry content type %content-type% is currently not supported.'
};
export default core_en;