var ExplainComponents_en = {
    noComponentSelected: "No component for description selected.",
    noDescription: "This component does not include a description.",
    datasets : "Dataset requirements",
    attributeName : "Name",
    attributeDesc : "Description",
    attributeReq : "Optional",
    attributesNone : "This component does not require special attributes in the data.",
    functions : "Functions",
    noFunctions : "This component has no external useable functions.",
    noParams : 'This method has no parameters',
    paramName : 'Name',
    paramDescription : 'Description',
    templates : "Available templates",
    template : "Template requirements",
    tplsNone : "This component has no Templates.",
    tmplelemSelector : "CSS selector",
    tmplelemDesc : "Description",
    tmplelemReq : "Optional",
    tmplelemsNone : "This component has no requiements for a template",
    styles : "Styles",
    styleSelector : "CSS Selecto to activate style",
    styleDesc : "Description",
    stylesNone : "This component does not have styles.",
    dependencies : "Dependencies",
    dependenciesName : "Name",
    dependenciesDesc : "Description",
    dependenciesPath : "Path",
    dependenciesNone : "This component has no dependencies.",
    options : "Options",
    optionsNone : "This component has no Options",
    optionsName : "Name",
    optionsDesc : "Description",
    optionsNodesc : "This options was not documented.",
    optionsDefault : "Default",
    optionsExample: "Example",
    optionsNoExample: "No example available",
    plugins: "Plugins"
};
export default ExplainComponents_en;