#!/bin/bash

#Name der Tabelllen die geladen werden sollen
tables=(FlagMS7 MS700SMS1 RadSMS1 CmpSMS1 TmpSMS1 TotSMS1 StaSMS1 CmpSMS1_10sec)

#Datei in der das letzte Datum gespeichert wird
file=/home/mpp/cr1000/logger/lastdate.bkup

#IP-Adresse der Anlage
ipaddr=194.95.176.15

#Verzeichniss für die Dateien
dir=/home/mpp/cr1000

datum=$(date +"%Y-%m-%d-%H-%M-%S")
aktDate=$(date -u +"%Y-%m-%dT%T")

backupDate=`head -n 1 $file`
echo Holde Daten seit: $backupDate

echo $aktDate > $file

for table in ${tables[*]}
do
	echo Catch $table
	curl -o "$dir/$table.$datum.xml" "http://$ipaddr/?command=dataquery&uri=dl:$table&format=xml&mode=since-time&p1=$backupDate"
done
