var User_de = {
    login: 'Login',
    enterlogindata: 'Please enter your login data.',
    username: 'Username',
    userpwd: 'Password',
    loginprogress: 'Login is in progress. Please wait...',
    nologinpossible: 'Sorry, login is currently not possible',
    logout: 'Logout',
    registerhere: 'Register now',
    pwdlost: 'Forgott password?',
    regconfirminfo: 'Please enter your confirmation code.',
    regconfirm: 'Confirm registration',
    regconfirmed: 'Registration confirmed. You can login now.',
    accept_privacy: 'You have to accept our <a href="%privacy_url%" target="_new">Privacy statement</a>.',
    accept_terms: 'You have to accept our <a href="%terms_url%" target="_new">Terms of use</a>.',
    accept_privacy_terms: 'You have to accept our <a href="%terms_url%" target="_new">Terms of use</a> and <a href="%privacy_url%" target="_new">Privacy statement</a>.',
    dontaccept: 'I deny',
    accept: 'I accept',
    notaccepted_terms: 'You did not accept the terms and can not use this service any longer.',
    maillogininfo: "Please enter your username or email to recive an email for one time login.",
    maillogin: "Send email",
    mailloginsend: "We send you an email if your username or email exists.",
    mailloginfail: "You can't logged in. Eventually you used this One-Time-Login before.",
    account: "Account",
    autologout: "You are automatically logged out",
    regtokenhere: 'Insert characters from email here'
};
export default User_de;