var Edit_en = {
    noinputdef: "Could not generate input fields. There are no input definitions.",
    errorcreateform: "Error while createing the form.",
    errorgetoptions: "Error while getting select options.",
    forgotteninput: "Not all fields are filled or there are some wrong filled fields.",
    noObjectTemplates: "There are no possible entries defined.",
    formlegend: "Edit dataset",
    adddataset: "Add",
    addsavefirst: "Please first save the last created dataset.",
    loadingeditform: "Loading edit form",
    editor: "Editor",
    newdataset: "New dataset",
    editdataset: "Edit dataset",
    valuerequired: "Please enter a value for %attrname%.",
    noselection: "No selection",
    drophere: "Drop here",
    dropNotAccepted: "This element can not be assigned here.",
    dropFetchError: "Could not load elements data.",
    couldnotsave: "Could not save data",
    refDelete: "Delete connection",
    save: "Save",
    delchild: "Delete",
    filesourcenotsupported: "You can't use this function on data from files.",
    groupeditbtn: 'Groupeditmode',
    groupedit: 'Groupeditmode: If you change a value all values of similar input fields will change, too.',
    autodata_start: 'Start automatic data update',
    autodata_stop: 'Stop automtic data update',
    autodata_requestor_err: 'Error getting data.',
    autodata_script_err: 'Could not calculate data.',
    autodata_requestor_nodata: 'No data available'
};
export default Edit_en;