name: Java CI

on:
  push:
    branches:
      - main
      - dev
    paths:
      - 'backend/projects/SmartSocial/**'
  pull_request:
    branches:
      - main
      - dev
    paths:
      - 'backend/projects/SmartSocial/**'
  workflow_dispatch: # This line enables manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Build with Gradle
      run: ./gradlew build -x test
      working-directory: backend/projects/SmartSocial
