var Upload_en = {
  selectfile: "Drag one or more files here",
  draganddropfile: "or select one here.",
  toupload: 'uploaded',
  uploaded: 'uploading',
  saved: 'saved',
  notsaved: 'upload not saved',
  preuploaderror: 'An error occured while preparing the upload',
  upload_errnotfound: 'The target for the upload was not found.',
  upload_errother: 'An error occured while uploading.',
  addatamissing: 'There are missing inputs in the form',
  noprocessoravailable: "There is no parser available for this file",
  canbeprocessedby: 'Choose a parser to interpret this file:',
  startprocessing: 'Start processing',
  processed: 'Processed',
  processingFailed: 'Processing failed',
  processingSuccseed: 'Processing successful',
  notprocessed: 'The file could not be processed.',
  erroroccured: 'An error occured',
  uploadFilesButton: 'Upload pending files',
  removeFilesButton: 'Remove all files',
  column_file: 'File',
  column_type: 'Type',
  column_status: 'Status',
  column_remove: 'Remove',
};
export default Upload_en;